# Generated by Django 3.1.4 on 2021-06-05 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gost', models.CharField(max_length=8, verbose_name='Профстандарт')),
            ],
            options={
                'verbose_name': 'Профстандарт',
                'verbose_name_plural': 'Профстандарты',
            },
        ),
        migrations.CreateModel(
            name='Labor_functions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Название раздела')),
                ('code_gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_files.gost', verbose_name='Код профессии')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Испытуемый',
                'verbose_name_plural': 'Испытуемые',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Вопрос')),
                ('type_test', models.CharField(max_length=6, verbose_name='Тип вопроса')),
                ('code_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_files.labor_functions', verbose_name='Код раздела')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='labor_functions',
            name='code_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_files.professions', verbose_name='Код профессии'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='Ответ')),
                ('answered', models.DateField()),
                ('code_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_files.tests', verbose_name='Код вопроса')),
                ('code_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_files.users', verbose_name='Код пользователя')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
